### ISSUE TITLE
The scripts returns ERROR

### ISSUE THREAD

**Issue by gdamdam** [orjail/orjail#52]
so, I've tried the script but it returns only error.

this what I've done:
``
git clone https://github.com/orjail/orjail.git
cd orjail/user/sbin
sudo ./orjail -v
``

it returns:
``
[Error] exit ""
 * Remove Tor temporary configuration
 * Killing Tor process 
 * Killed 
 * Remove Tor DataDirectory: /tmp/orjail-orjail
 * Remove in-orjail network interface
Cannot find device "in-orjail"
 * Delete network namespace orjail
Cannot remove namespace file "/var/run/netns/orjail": No such file or directory
 * Cleaning up iptables rules...
``

please HALP!

**Comment by gdamdam** [comment]
I tried it on Ubuntu and Debian:
Ubuntu: Linux computer 4.15.0-24-generic #26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Debian: Linux computer 4.17.0-1-amd64 #1 SMP Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux

**Comment by gdamdam** [comment]
I can't figure out what is the missing program....

so... running `sudo ./orjail -v -s`  I have the following error:

 * Executing Tor...
Sep 18 13:01:25.800 [notice] Tor 0.3.4.8 (git-5da0e95e4871a0a1) running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.0h, Zlib 1.2.11, Liblzma 5.2.2, and Libzstd 1.3.5.
Sep 18 13:01:25.800 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Sep 18 13:01:25.800 [notice] Read configuration file "/tmp/torf6Wusf".
Sep 18 13:01:25.804 [notice] You configured a non-loopback address '10.200.1.1:5354' for DNSPort. This allows everybody on your local network to use your machine as a proxy. Make sure this is what you wanted.
Sep 18 13:01:25.804 [notice] You configured a non-loopback address '10.200.1.1:9040' for TransPort. This allows everybody on your local network to use your machine as a proxy. Make sure this is what you wanted.
Sep 18 13:01:25.804 [warn] /var/lib/tor/other_hidden_service/ is not owned by this user (root, 0) but by debian-tor (108). Perhaps you are running Tor as the wrong user?
Sep 18 13:01:25.804 [warn] Failed to parse/validate config: Failed to configure rendezvous options. See logs for details.
Sep 18 13:01:25.804 [err] Reading config failed--see warnings above.
[Error] ""

I have TOR installed: `Tor version 0.3.4.8 (git-5da0e95e4871a0a1)`

trying to use the `-f` for firejail I have another error:
`orjail requires at least firejail 0.99.44.10 to run.
[Error] exit 1`

but I have installed the last stable version from sources

$ firejail --version
firejail version 0.9.56

**Comment by lesion** [comment]
first of all, thanks for reporting :smile:
I thing I've fixed all the issue with the last commits:

- first issue was due to your own /etc/tor/torrc (`orjail` included your host `/etc/tor/torrc` by default, now is included with `--host-torrc` flag) -> https://github.com/orjail/orjail/commit/044cd9ee2c6ce15386c3d3a1b8110331ef8c8630 (in particular you had an hidden service enabled, incompatible with orjail that has a specific flag for it `-H`)
- another issue was the error not printed -> https://github.com/orjail/orjail/commit/00961d51514b68b5524356e15b74bc23ef59b2c0
- the last error is really strange, the only thing I can think about, is that you don't have `bc`, I'm now checking it -> https://github.com/orjail/orjail/commit/efea5a04f1911f4c0300a460bd3cca8476e44c8f

**Comment by gdamdam** [comment]
hei hei hei! Last commit fixed the problem!!  `orjail` looks promising! I like it.
(just for the record `bc` was installed)
f i g a t a 
grazie lesion
